// This file is auto-generated by @hey-api/openapi-ts

export type EmptySchema = {
    [key: string]: unknown;
};

export type AuthSchema = {
    is_authenticated: boolean;
    msg?: string | null;
    user?: UserSchema | null;
};

export type UserSchema = {
    id: number;
    username: string;
    email: string | null;
    first_name: string;
    last_name: string;
    pic_url: string | null;
    full_name: string;
    is_admin: boolean;
    initials: string;
    permissions: Array<string>;
};

export type LoginSchema = {
    username: string;
    password: string;
};

export type ChangePasswordOutputSchema = {
    is_success: boolean;
    msg: string;
};

export type ChangePasswordInputSchema = {
    old_password: string;
    new_password: string;
};

export type CheckTemporaryAccessSchema = {
    user_id: number;
    access_id: string;
};

export type ForgotMyPasswordSchema = {
    email: string;
};

export type ChangePasswordByAccessIdSchema = {
    user_id: number;
    access_id: string;
    new_password: string;
};

export type AuthViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/';
};

export type AuthViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type AuthViewResponse = AuthViewResponses[keyof AuthViewResponses];

export type LoginViewData = {
    body: LoginSchema;
    path?: never;
    query?: never;
    url: '/auth/login/';
};

export type LoginViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type LoginViewResponse = LoginViewResponses[keyof LoginViewResponses];

export type LogoutViewData = {
    body: EmptySchema;
    path?: never;
    query?: never;
    url: '/auth/logout/';
};

export type LogoutViewResponses = {
    /**
     * OK
     */
    200: AuthSchema;
};

export type LogoutViewResponse = LogoutViewResponses[keyof LogoutViewResponses];

export type ChangePasswordViewData = {
    body: ChangePasswordInputSchema;
    path?: never;
    query?: never;
    url: '/auth/change-password/';
};

export type ChangePasswordViewResponses = {
    /**
     * OK
     */
    200: ChangePasswordOutputSchema;
};

export type ChangePasswordViewResponse = ChangePasswordViewResponses[keyof ChangePasswordViewResponses];

export type CheckTemporaryAccessViewData = {
    body: CheckTemporaryAccessSchema;
    path?: never;
    query?: never;
    url: '/auth/check-temporary-access/';
};

export type CheckTemporaryAccessViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type CheckTemporaryAccessViewResponse = CheckTemporaryAccessViewResponses[keyof CheckTemporaryAccessViewResponses];

export type ForgotMyPasswordViewData = {
    body: ForgotMyPasswordSchema;
    path?: never;
    query?: never;
    url: '/auth/forgot-my-password/';
};

export type ForgotMyPasswordViewResponses = {
    /**
     * OK
     */
    200: EmptySchema;
};

export type ForgotMyPasswordViewResponse = ForgotMyPasswordViewResponses[keyof ForgotMyPasswordViewResponses];

export type ChangePasswordByAccessIdViewData = {
    body: ChangePasswordByAccessIdSchema;
    path?: never;
    query?: never;
    url: '/auth/change-password-by-access-id/';
};

export type ChangePasswordByAccessIdViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type ChangePasswordByAccessIdViewResponse = ChangePasswordByAccessIdViewResponses[keyof ChangePasswordByAccessIdViewResponses];

export type ClientOptions = {
    baseUrl: string;
};