// This file is auto-generated by @hey-api/openapi-ts

export type BlockTypes = 'round' | 'square' | 'triangle';

export type PaginationBlockFilterSchema = {
    a?: string | null;
    c?: string | null;
    search?: string | null;
    block_type?: BlockTypes | null;
};

export type PaginationQueryParams = {
    page?: number;
    page_size?: number;
    order_by?: Array<string> | null;
};

export type EmptySchema = {
    [key: string]: unknown;
};

export type BlockSchema = {
    id: number;
    a: string;
    b: number;
    c: boolean;
    block_type: BlockTypes;
};

export type PaginationOutputBlockSchema = {
    total_amount: number;
    pages_amount: number;
    page: number;
    page_size: number;
    data: Array<BlockSchema>;
};

export type CreateBlockItemSchema = {
    a: string;
    b: string;
    c: string;
    block_type: BlockTypes;
};

export type ItemByIdPath = {
    object_id: number;
};

export type PatchBlockItemSchema = {
    a: string | null;
    b: number | null;
    c: boolean | null;
};

export type RunActionBuildBlockItemSchema = {
    should_build: boolean;
};

export type PostSampleWebsocketViewSchema = {
    room_id: number;
};

export type PaginationBlockViewData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        page_size?: number;
        order_by?: Array<string> | null;
        a?: string | null;
        c?: string | null;
        search?: string | null;
        block_type?: BlockTypes | null;
    };
    url: '/api/blocks/';
};

export type PaginationBlockViewResponses = {
    /**
     * OK
     */
    200: PaginationOutputBlockSchema;
};

export type PaginationBlockViewResponse = PaginationBlockViewResponses[keyof PaginationBlockViewResponses];

export type PostCreateBlockItemViewData = {
    body: CreateBlockItemSchema;
    path?: never;
    query?: never;
    url: '/api/blocks/';
};

export type PostCreateBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type PostCreateBlockItemViewResponse = PostCreateBlockItemViewResponses[keyof PostCreateBlockItemViewResponses];

export type DeleteBlockItemViewData = {
    body?: EmptySchema;
    path: {
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/';
};

export type DeleteBlockItemViewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReadBlockItemViewData = {
    body?: never;
    path: {
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/';
};

export type ReadBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type ReadBlockItemViewResponse = ReadBlockItemViewResponses[keyof ReadBlockItemViewResponses];

export type UpdateBlockItemViewData = {
    body: PatchBlockItemSchema;
    path: {
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/';
};

export type UpdateBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type UpdateBlockItemViewResponse = UpdateBlockItemViewResponses[keyof UpdateBlockItemViewResponses];

export type RunActionBuildBlockItemViewData = {
    body: RunActionBuildBlockItemSchema;
    path: {
        object_id: number;
    };
    query?: never;
    url: '/api/blocks/{object_id}/build/';
};

export type RunActionBuildBlockItemViewResponses = {
    /**
     * OK
     */
    200: BlockSchema;
};

export type RunActionBuildBlockItemViewResponse = RunActionBuildBlockItemViewResponses[keyof RunActionBuildBlockItemViewResponses];

export type PostSampleWebsocketViewData = {
    body: PostSampleWebsocketViewSchema;
    path?: never;
    query?: never;
    url: '/api/blocks/websocket-test/';
};

export type PostSampleWebsocketViewResponses = {
    /**
     * OK
     */
    200: EmptySchema;
};

export type PostSampleWebsocketViewResponse = PostSampleWebsocketViewResponses[keyof PostSampleWebsocketViewResponses];

export type ClientOptions = {
    baseUrl: string;
};