version: '3.8'

services:
  example_db:
    restart: always
    shm_size: 6G
    image: postgres:14-alpine
    volumes:
      - example_db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=km3C465odLfr44f
      - POSTGRES_DB=example_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - dev-network
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 6G

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - dev-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    expose:
      - 5672
    restart: on-failure
    networks:
      - dev-network

volumes:
  example_db_data:

networks:
  dev-network: