version: '3.8'

name: example_project_docker_group
services:
  example_db:
    restart: always
    shm_size: 6G
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=<db_password>
      - POSTGRES_DB=example_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    expose:
      - 5672
    restart: on-failure
    networks:
      - network

volumes:
  db_data:
  rabbitmq_data:
  logs:

networks:
  network: