// This file is auto-generated by @hey-api/openapi-ts

export type EmptySchema = {
    [key: string]: unknown;
};

export type FullConfigurationsOutput = {
    timezones: Array<string>;
};

export type FullConfigurationsViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/configurations/';
};

export type FullConfigurationsViewResponses = {
    /**
     * OK
     */
    200: FullConfigurationsOutput;
};

export type FullConfigurationsViewResponse = FullConfigurationsViewResponses[keyof FullConfigurationsViewResponses];

export type ClientOptions = {
    baseUrl: string;
};