// This file is auto-generated by @hey-api/openapi-ts

export type EmptySchema = {
    [key: string]: unknown;
};

export type UserSchema = {
    id: number;
    username: string;
    email: string | null;
    first_name: string;
    last_name: string;
    pic_url: string | null;
    full_name: string;
    is_admin: boolean;
    initials: string;
    permissions: Array<string>;
};

export type MyUserItemViewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/my/';
};

export type MyUserItemViewResponses = {
    /**
     * OK
     */
    200: UserSchema;
};

export type MyUserItemViewResponse = MyUserItemViewResponses[keyof MyUserItemViewResponses];

export type ClientOptions = {
    baseUrl: string;
};