# Generated by Django 4.2.4 on 2023-08-16 16:28

import common.db_fields.list_field_with_choices
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(blank=True, default='')),
                ('b', models.IntegerField(blank=True, default=0)),
                ('c', models.BooleanField(blank=True, default=False)),
                ('block_type', common.db_fields.list_field_with_choices.ListFieldWithChoices(base_field=models.CharField(blank=True, choices=[], max_length=100, null=True), blank=True, default=list, size=None)),
            ],
        ),
    ]
