# Generated by Django 4.2.4 on 2023-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(blank=True, choices=[('round', 'round'), ('square', 'square'), ('triangle', 'triangle')], default='round', max_length=255),
        ),
    ]
