# Generated by Django 4.2.4 on 2023-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=str, max_length=255)),
                ('data', models.JSONField(blank=True, default=None)),
                ('name_hash', models.CharField(blank=True, default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailsConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender_type', models.CharField(choices=[('none', 'none'), ('mandrill', 'mandrill')], default='none', max_length=30)),
                ('email_sender_params', models.JSONField(blank=True, default=dict)),
                ('marketing_platform_type', models.CharField(choices=[('none', 'none'), ('mailchimp', 'mailchimp')], default='none', max_length=30)),
                ('marketing_platform_params', models.JSONField(blank=True, default=dict)),
                ('email_validation_type', models.CharField(choices=[('none', 'none'), ('zerobounce', 'zerobounce')], default='none', max_length=30)),
                ('email_validation_params', models.JSONField(blank=True, default=dict)),
                ('send_emails', models.BooleanField(blank=True, default=False)),
                ('emails_for_testing', models.JSONField(blank=True, default=list)),
                ('rnd_admin_emails', models.JSONField(blank=True, default=list)),
                ('contact_us_link', models.TextField(blank=True, default='')),
                ('privacy_link', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GUIConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gui_hostname', models.CharField(blank=True, default='', max_length=200)),
                ('backend_hostname', models.CharField(blank=True, default='', max_length=200)),
                ('default_profile_pic', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(blank=True, choices=[('none', 'none'), ('azure_storage', 'azure_storage')], default='none', max_length=100)),
                ('storage_params', models.JSONField(blank=True, default=dict)),
                ('dev_storage_type', models.CharField(blank=True, choices=[('none', 'none'), ('azure_storage', 'azure_storage')], default='none', max_length=100)),
                ('dev_storage_params', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsersEventsConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_analyze_events', models.BooleanField(blank=True, default=False)),
                ('events_analysis_params', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
